server.port=8083
spring.application.name=order-service
spring.datasource.url=jdbc:mysql://localhost:3306/order_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Inventory service base URL (for stock deduction on sales order fulfillment)
inventory.service.url=http://localhost:8082
